version: '3'

services:

  api:
    image: 'tmvdl/projects:alibaba-app'
    hostname: api
    build: './src/api'
    volumes:
      - './src/api:/app'
      - './data:/data'
    ports:
      - '8000:80'
